@startuml
'https://plantuml.com/activity-diagram-beta
|system|
start
:<&script> Query "has saved login credentials";
-> [flag];
if () then ([flag == yes])
else ([flag == no])
    |user|
    :<&person> Submit login credentials;
    -> [Login credentials];
    |system|
    : <&script> Save login credentials;
endif
    :Send "Start Present Summary"; <<output>>
    stop;
@enduml
