@startuml
'https://plantuml.com/activity-diagram-beta
|system|

start

floating note left
Level: Subfunction
Trigger: none
Primary Actor: User
end note


:<&script> Query "has saved login credentials";
-> [flag];
if () then ([flag == yes])
else ([flag == no])
    |user|
    :<&person> Submit login credentials;
    -> [Login credentials];
    |system|
    : <&script> Save login credentials;
endif
    stop;
@enduml
