@startuml
'https://plantuml.com/activity-diagram-beta

|system|
start

'This is the case of "Two levels of blue"
floating note left
Level: User goal
Trigger: User selects to
    create a savings goal after
    being presented with Accounts
    and Round-up Summary,
    or during Transfer Round-up
    before selecting Savings Goal
Primary Actor: User
Precondition: User has been presented with
  Accounts and Round-ups Summary
  or Transfer Round-up extension
  point has been reached.
end note

|system|
|user|
:<&person> Submit goal name;
-> [name];
|system|
:<&script> Query context from Transfer Round-up;
-> [accountId, accountCurrency];
:<&cog> Create Savings Goal;

:Send Close Create Savings Goal UI; <<sendSignal>>
:Send Data Source Changed; <<sendSignal>>

stop

@enduml
