@startuml
'https://plantuml.com/activity-diagram-beta

|system|
start

floating note left
TODO this use case can be
about a broader personal finance summary
including savings goals and
their balance which would allow
to user to make informed
financial decisions, e.g.
creating additional savings
goals or transferring to
savings goals that
are lagging behind.

Level: User goal
Trigger: User launches the app
    or selects to refresh summary
Primary Actor: User
Precondition: none
endnote

: <&plus> Ensure Login Credentials;
-> [Outcome];

:TODO handle the outcome;

:<&script> Get current date and time;
-> [Date and time];
:<&spreadsheet> Calculate the start of the week-long period;
-> [Date and time];
repeat
 :<&cog> Fetch accounts and their transactions
since the start of the period;
-> [Result];

if () then ([is Auth Error])
    :Present unrecoverable error message and ask to Log out; <<sendSignal>>
    stop
endif

if () then ([is Network Error or is API Error])
    |user|
    :<&person> Confirm retrying recovery
    from error;
    |system|
else ([is Result set])
    :<&spreadsheet> Summarize;
    -> [Summary];
    :Present Summary; <<sendSignal>>
    stop
endif

-> [Confirmation result];
repeat while () is ([is OK])
-> [is Cancel] - [Error];
stop
@enduml
