@startuml
'https://plantuml.com/activity-diagram-beta

'TODO refine
|user|
start

floating note left
Level: User Goal
Trigger: User selects to log out
Primary Actor: User
Precondition: The user has provided
    login credentials
end note

|app|
:Erase saved credentials;
:Erase any user specific data;
:Restarts the app;
stop

@enduml
