@startuml
'https://plantuml.com/activity-diagram-beta

|system|
start

floating note left
Level: User Goal
Trigger: User selects an account
  from Accounts and Round-ups
  Summary to transfer round-ups from
Primary Actor: User
Precondition: Accounts and Round-ups
  Summary has been presented
endnote

'passed to SavingsGoalsFragment
-> [accountId,
accountCurrency,
roundUpAmount];

'ListSavingGoalsInteractor
: <&cog> Fetch savings goals;
-> [Result];

'SavingsGoalsViewModel
if () then ([is Service Error])
    'displays a dialog, not a snackbar
    'doesn't return to the main screen
    :Present unrecoverable error message; <<sendSignal>>
    stop
endif

-> [list of Savings Goals];

|user|
:Select a savings goal
(extension point: Savings Goals CRUD);

|system|
'passed to TransferConfirmationFragment
->[savingsGoal,
roundUpAmount,
accountCurrency,
accountId]
;

repeat
'TransferConfirmationViewModel
:<&spreadsheet> Summarize transfer;

|user|
:Confirm transfer;
-> [accountId,
savingsGoalId,
accountCurrency,
roundUpAmount];
|system|
'AddMoneyIntoGoalInteractor
: <&cog> Add money into goal;
-> [Result];

'displays a dialog, not a snackbar
backward: Present unrecoverable error message; <<sendSignal>>

repeat while () is ([is Service Error])
-> [OK];

'TransferConfirmationViewModel
'and returns to the main screen - navigationChannel.send(Navigation.Before(R.id.savingsGoalsDestination))
:Send success acknowledgement; <<sendSignal>>

stop

@enduml
