@startuml
'https://plantuml.com/activity-diagram-beta

|system|
start

floating note left
Level: User Goal
Trigger: User selects an account
  from Accounts and Round-ups
  Summary to transfer round-ups from
Primary Actor: User
Precondition: Accounts and Round-ups
  Summary has been presented
endnote

'passed to SavingsGoalsFragment
-> [accountId,
accountCurrency,
roundUpAmount,
savingsGoalId];

repeat
: <&cog> Add money into goal;
-> [Result];

'displays a dialog, not a snackbar
backward: Present unrecoverable error message; <<sendSignal>>

repeat while () is ([is Service Error])
-> [OK];

:Present success acknowledgement; <<sendSignal>>

stop

@enduml
