@startuml
'https://plantuml.com/activity-diagram-beta

|system|
start

floating note left
Level: User Goal
Trigger: User selects an account
  from Accounts and Round-ups
  Summary to transfer round-ups from
Primary Actor: User
Precondition: Accounts and Round-ups
  Summary has been presented
endnote

'passed to SavingsGoalsFragment
-> [accountId,
accountCurrency,
roundUpAmount];

: <&cog> Fetch savings goals;
-> [Result];

if () then ([is Service Error])
    'displays a dialog, not a snackbar
    'doesn't return to the main screen
    :Present unrecoverable error message; <<sendSignal>>
    stop
endif

-> [list of Savings Goals];

|user|
:Select a savings goal
(extension point: Savings Goals CRUD);

|system|
->[savingsGoalId]
;

repeat
:<&spreadsheet> Gather transfer details;

-> [roundUpAmount, accountCurrency, goalName] ;

|user|
:Confirm transfer;
|system|
'AddMoneyIntoGoalInteractor
: <&cog> Add money into goal;
-> [Result];

'displays a dialog, not a snackbar
backward: Present unrecoverable error message; <<sendSignal>>

repeat while () is ([is Service Error])
-> [OK];

:Present success acknowledgement; <<sendSignal>>

stop

@enduml
