@startuml
'https://plantuml.com/use-case-diagram

'Includes the subfunction level use cases

left to right direction
actor Customer
actor "Banking API"

rectangle System {
usecase "View Summary"
usecase "Log out"
usecase "Ensure Login Credentials"
usecase "Transfer Round-up"
usecase "Create Savings Goal"
}

Customer -- "View Summary"
Customer -- "Transfer Round-up"
Customer -- "Create Savings Goal"
Customer -- "Log out"

"View Summary" -- "Banking API"
"View Summary" .> "Ensure Login Credentials": <<includes>>
"Transfer Round-up" -- "Banking API"
"Create Savings Goal" -- "Banking API"
@enduml