@startuml
'https://plantuml.com/use-case-diagram

' Level: User Goals

left to right direction
actor User <<Human>>
actor Bank <<Service>>

rectangle System {
usecase "Get Summary"
usecase "Log out"
usecase "Transfer Round-up"
usecase "Create Savings Goal"
}

User -- "Get Summary"
User -- "Transfer Round-up"
User -- "Create Savings Goal"
User -- "Log out"

"Get Summary" -- "Bank"
"Create Savings Goal" .> "Transfer Round-up" : <<extend>>
"Transfer Round-up" -- "Bank"
"Create Savings Goal" -- "Bank"
@enduml