@startuml
'https://plantuml.com/activity-diagram-beta

'TODO refine
|user|
start
floating note left: Preconditions: The user\n\
has already logged in
|app|
:Erases saved credentials;
:Erases any user specific data;
:Restarts the app;
stop

@enduml
