@startuml
'https://plantuml.com/activity-diagram-beta

|app|
start
:Caclulate the start of the week-long period;
:Fetch accounts and transactions
for the week-long period.
(service task);
:Generate report
(business rule task);
:Show report
(send task);
stop

@enduml
