@startuml
'https://plantuml.com/activity-diagram-beta

|app|
start
:Get current date and time;
:Date and time ]
'<<businessRule>>
:ƒ Calculate the start of the week-long period;
:Date and time ]
'<<serviceCall>>
:⚙ Fetch accounts and thier transactions
since the start of the period;
:Result set ]
'<<businessRule>>
:ƒ  Summarize;
:Summary]
:Present Summary >
stop

@enduml
