@startuml
'https://plantuml.com/activity-diagram-beta

|app|
start
:<&script> Get current date and time;
-> [Date and time];
'<<businessRule>>
:<&spreadsheet> Calculate the start of the week-long period;
-> [Date and time];
'<<serviceCall>>
:<&cog> Fetch accounts and thier transactions
since the start of the period;
-> [Result set];
'<<businessRule>>
:<&spreadsheet> Summarize;
-> [Summary];
:Present Summary >
stop

@enduml
