@startuml
'https://plantuml.com/activity-diagram-beta

|app|
start
:Get current date and time;
:Date and time ]
'<<businessRule>>
:ƒ Caclulate the start of the week-long period;
:Date and time ]
'<<serviceCall>>
:⚙ Fetch accounts and transactions
since the start of the period;
:Dataset ]
'<<businessRule>>
:ƒ  Generate report;
:Report ]
:Present report >
stop

@enduml
