@startuml
'https://plantuml.com/activity-diagram-beta

|app|
start
:<&script> Get current date and time;
-> [Date and time];
:<&spreadsheet> Calculate the start of the week-long period;
-> [Date and time];
repeat
 :<&cog> Fetch accounts and thier transactions
since the start of the period;
-> [result];
backward: <&person> Confrirm retry recover from [Error];
repeat while (result type?) is (Netwrok Error or Service Error)
if (result type?) then (Auth Error)
end
endif
-> [Result set];
:<&spreadsheet> Summarize;
-> [Summary];
:Present Summary >
stop

@enduml
