@startuml
'https://plantuml.com/activity-diagram-beta
|user|
start
floating note left: Preconditions: The user\n\
has already logged in
|app|
:Provides a form;
|user|
:Submits choices of account and savings goal;
|app|
:Calls addMoneyIntoSavingsGoal;
:Provides an acknowledgement;
:Provides a report of goals and accounts along with round-ups;
stop

@enduml
