@startuml
'https://plantuml.com/activity-diagram-beta
|app|
start
note left
Launch app event
end note
if (Has saved login credentials?) then (yes)
else (no)
    |user|
    :Submit login credentials
    (user task);
    |app|
    :Save login credentials;
endif
    :Present Accounts and Roundups
    (subprocess);

stop

@enduml
