@startuml
'https://plantuml.com/activity-diagram-beta
|system|
start
repeat
:<&script> Query "has saved login credentials";
-> [flag];
if () then ([flag == yes])
else ([flag == no])
    |user|
    :<&person> Submit login credentials;
    -> [Login credentials];
    |system|
    : <&script> Save login credentials;
endif
    :⊞ Present Accounts and Roundups
    Summary;
    -> [Result];

    if () then  ([is Auth Error])
        :<&script> Clear user data;
        :Present error message >
        -> [auth error];
        |user|
        :<&person> Confirm submit again;
        |system|
    elseif () then  ([is other error])
        end
    else (is ok)
        stop
    endif
    |system|
repeat while () is ([is Confired])
end
@enduml
