@startuml
'https://plantuml.com/activity-diagram-beta
|app|
start
note left
Launch app event
end note
:<&script> Query "has saved login credentials";
-> [flag];
if (has saved login credentials) then (flag == yes)
else (flag == no)
    |user|
    :<&person> Submit login credentials;
    -> [Login credentials];
    |app|
    : <&script> Save login credentials;
endif
    :⊞ Present Accounts and Roundups
    Summary;
note left
This will fail if login
credentials are invalid
end note
stop

@enduml
