@startuml
'https://plantuml.com/activity-diagram-beta

start
:<&person> Choose Savings Goal;
:<&spreadsheet> Summarize;
-> [Transfer Summary];
:<&person> Confirm Transfer;
:Acknowledgement >

stop

@enduml
