@startuml
'https://plantuml.com/use-case-diagram

left to right direction
actor User

rectangle System {
usecase Startup
usecase Logout
usecase "Save Round-ups"
usecase "Create Savings Goal"
usecase "Present 'Accounts and Round-ups'"
}

User --> Startup
User --> "Save Round-ups"
User --> "Create Savings Goal"
User --> "Logout"

Startup .> "Present 'Accounts and Round-ups'"
"Save Round-ups" .> "Present 'Accounts and Round-ups'"

@enduml