@startuml
'https://plantuml.com/use-case-diagram

left to right direction
actor User

rectangle System {
usecase Startup
usecase Logout
usecase "Save Round-ups"
usecase "Create Savings Goal"
usecase "Show Accounts and Roundups report"
}

User --> Startup
User --> "Save Round-ups"
User --> "Create Savings Goal"
User --> "Logout"

Startup .> "Show Accounts and Roundups report"
"Save Round-ups" .> "Show Accounts and Roundups report"

@enduml