@startuml
'https://plantuml.com/use-case-diagram

left to right direction
actor User <<Human>>
actor Bank <<Service>>

rectangle System {
usecase Startup
usecase Logout
usecase "Transfer Round-up"
usecase "Create Savings Goal"
usecase "Present Summary"
}

User -- Startup
User -- "Transfer Round-up"
User -- "Logout"
User -- "Present Summary"

Startup .> "Present Summary" : <<include>>
"Transfer Round-up" .> "Present Summary" : <<include>>
"Create Savings Goal" .> "Transfer Round-up" : <<extend>>
"Present Summary" -- "Bank"
"Transfer Round-up" -- "Bank"
"Create Savings Goal" -- "Bank"
@enduml