name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  # NOTE: "each job in a workflow runs in a fresh virtual environment"
  verify_branch_job:
    name: Verify Branch
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      # NOTE: "Jobs on GitHub-hosted runners start in a clean virtual environment and must download
      # dependencies each time, causing increased network utilization, longer runtime, and increased
      # cost. To help speed up the time it takes to recreate these files, GitHub can cache dependencies
      # you frequently use in workflows."
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build APK
      # Make sure the branch code can produce final deliverables (APKs) by merging manifest files,
      # other resources etc.
      run: bash ./gradlew assemble
